version: 0.0
os: linux
files:
  # - source:  /
  #   destination: /home/ec2-user/spring-simple-http-rest
  - source: /build/libs
    destination: /home/ec2-user/spring-simple-http-rest/build/libs
  - source: /.aws/aws-codedeploy-scripts
    destination: /home/ec2-user/spring-simple-http-rest/.aws/aws-codedeploy-scripts

file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: ./.aws/aws-codedeploy-scripts/stop.sh
      timeout: 30
      runas: ec2-user
  ApplicationStart:
    - location: ./.aws/aws-codedeploy-scripts/start.sh
      timeout: 60
      runas: ec2-user