# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle and CD by AWS CodeDeploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci-and-cd:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    - name: Make zip File
      run: zip -r ./build.zip ./build/libs/simple-http-rest-1.0.0.war ./appspec.yml ./.aws/aws-codedeploy-scripts
#      run: zip -r ./build.zip ./build/libs/*.war ./appspec.yml ./.aws/aws-codedeploy-scripts

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_CD_ID }}
        aws-secret-access-key: ${{ secrets.AWS_CD_SECRET }}
        aws-region: ap-northeast-2
        
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./build.zip s3://s3-cd-blackdeer/spring-simple-http-rest/build.zip
      
    - name: AWS CodeDeploy
      run: >
        aws deploy create-deployment
        --application-name test-spring-simple-rest
        --deployment-group-name cd-deploy-group-spring-simple-http-rest
        --deployment-config-name CodeDeployDefault.OneAtATime
        --s3-location bucket=s3-cd-blackdeer,bundleType=zip,key=spring-simple-http-rest/build.zip
